# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
sudo: false

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5
